### ISSUE TITLE
Two instances wrongly share their fields 

### ISSUE THREAD

**Issue by y-uti** [php-java/php-java#109]
# Tell me your versions
- **PHP**: `PHP 7.3.2 (cli) (built: Feb 17 2019 17:13:31) ( NTS )`
- **JDK**: `javac 1.8.0_212`
- **PHPJava**: `commit c793712e7b5565f1717ed2d5ade3bc19ec8c9784`

# Summary

Instances share their fields.

# Code

```php
public class A {
    public int value;
    public A(int value) { this.value = value; }
}
```

```php
<?php
require_once 'vendor/autoload.php';
use PHPJava\Core\JavaClass;
use PHPJava\Core\Stream\Reader\FileReader;

$invoker = (new JavaClass(new FileReader(__DIR__ . '/A.class')))->getInvoker();
function printValue($a) {
    echo $a->getDynamic()->getFields()->get('value')->getValue(), "\n";
}

$a1 = $invoker->construct(1); printValue($a1); // 1, as expected.
$a2 = $invoker->construct(2); printValue($a2); // 2, as expected.
printValue($a1); // expect 1, but 2.
```

# Expect

1

# Actual

2

**Comment by m3m0r7** [comment]
@y-uti 
Thanks for your reporting!
I'll fix it.

**Comment by memory-agape** [comment]
I did checked it, that is expected result.
Because $a1 JavaClass object as same as $a2 JavaClass object.
And, in PHPJava's `construct` only initialize dynamic fields.
(Does not construction new JavaClass instance.)

Your code rewrite by PHP as follows:

```php
<?php

class A
{
    public $value;
    public function __construct($value = null)
    {
        $this->value = $value;
        return $this;
    }
}


$invoker = new A();

$a1 = $invoker->__construct(1);
echo $a1->value . "\n";
$a2 = $invoker->__construct(2);
echo $a2->value . "\n";

var_dump($a1->value);
```

You need to generate new instance as below if you expect value is `1`.

```php
$classFile = __DIR__ . '/A.class';
$invoker1 = (new JavaClass(new FileReader($classFile)))->getInvoker();
$invoker2 = (new JavaClass(new FileReader($classFile)))->getInvoker();
function printValue($a) {
    echo $a->getDynamic()->getFields()->get('value')->getValue(), "\n";
}

$a1 = $invoker1->construct(1);
printValue($a1);
$a2 = $invoker2->construct(2);
printValue($a2);

printValue($a1);
```


Above proceeded result is below:

```
1
2
1
```

**Comment by m3m0r7** [comment]
@y-uti 

I checked it and ensured that was the expected result because the `$a1` JavaClass object is as same as the `$a2` JavaClass object.
And, in PHPJava's `construct`, it only initializes dynamic fields.
(Does not construct new JavaClass instance.)

Your code should be
rewriten in PHP as follows:

```php
<?php

class A
{
    public $value;
    public function __construct($value = null)
    {
        $this->value = $value;
        return $this;
    }
}


$invoker = new A();

$a1 = $invoker->__construct(1);
echo $a1->value . "\n";
$a2 = $invoker->__construct(2);
echo $a2->value . "\n";

var_dump($a1->value);
```

You need to generate a new instance shown below if your expected value is `1`:

```php
$classFile = __DIR__ . '/A.class';
$invoker1 = (new JavaClass(new FileReader($classFile)))->getInvoker();
$invoker2 = (new JavaClass(new FileReader($classFile)))->getInvoker();
function printValue($a) {
    echo $a->getDynamic()->getFields()->get('value')->getValue(), "\n";
}

$a1 = $invoker1->construct(1);
printValue($a1);
$a2 = $invoker2->construct(2);
printValue($a2);

printValue($a1);
```


The result is:

```
1
2
1
```

**Comment by y-uti** [comment]
Thank you for the information, but this is not limited to PHPJava's `construct` method.
For the following code, b1 and b2 should be different but PHPJava prints 'same'.
```
public class B {
    public static void main(String args[]) {
        B b1 = new B();
        B b2 = new B();
        System.out.println(b1 == b2 ? "same" : "not same");
    }
}
```

**Comment by m3m0r7** [comment]
@y-uti 
Thanks! Give me a few days for checking/solving those problems.

**Comment by m3m0r7** [comment]
I inspected the root cause, which is that the `new` opcode pushing the same `JavaClass` to the operand stack.

I'm fixing now at https://github.com/php-java/php-java/pull/116.
