### ISSUE TITLE
ConstantPool is read-only

### ISSUE THREAD

**Issue by chitoku-k** [php-java/php-java#120]
# What do you want to implement?
[java.lang.String#intern()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#intern())

# Example Code

```java
String te = "te";
String st = "st";

// Note that the interned instance is not stored to a variable.
// This method simply writes to the constant pool and returns `this`.
String test = te + st;
test.intern();

// test and "test" should be equal because the former instance is interned.
System.out.println(System.identityHashCode(test));
System.out.println(System.identityHashCode("test"));

// thus this should print `true`
System.out.println(test == "test");
```

# Expect

The current implementation of `ConstantPool` is set to read-only.

https://github.com/php-java/php-java/blob/7159b6f1d9ea69cf350d8f3dd4505b5303a5c953/src/Core/JVM/ConstantPool.php#L107

However, in order to implement this feature, `String#intern()` must be able to write to the instance so that the later reference to the literal `"test"` be interned `test`.

## See also:

Check what happens with `String.intern()`:
https://ideone.com/LZgCZR

and without `String.intern()`:
https://ideone.com/WFjmTf

**Comment by m3m0r7** [comment]
I talked with @chitoku-k.
Roughly, the implementation is going to be like:

In core side:
1) Make a new class `JVM\Intern\StringPool`
2) When `astore` opcode is called, find an interned string from `StringPool`.
And if it is found, push the interned string to an operand stack; otherwise, use a string that is already passed.

In `java.lang.String` package side:
1) writes to a pair of the `label` and `refer ConstantPool object` to the `StringPool`.

**Comment by m3m0r7** [comment]
@chitoku-k 
Hi!

I added a new annotation, `@provider`.
`@provider` annotation provides some features from `JavaClass`, `JavaClassInvoker` and so on.
In the case below, it is providing the `InternProvider` from `JavaClassInvoker`. 
The InternProvider enables an access to the intern's heap-space.

You need to change file as follows:

- \PHPJava\Packages\java\lang\_String#intern (This is an example.)

```php
    /**
     * Returns a canonical representation for the string object.
     *
     * @native ConstantPool
     * @provider InternProvider
     * @param mixed $a
     * @return mixed
     * @throws NotImplementedException
     * @see https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/package-summary.html#intern
     */
    public function intern(ConstantPool $cp, InternProvider $internProvider)
    {
        foreach ($cp->getEntries() as $entry) {
            if (!($entry instanceof \PHPJava\Kernel\Structures\_Utf8)) {
                continue;
            }
            if ($entry->getString() === (string) $this) {
                $internProvider->get(StringIntern::class)[spl_object_id($this)] = $entry;
                return;
            }
        }
        // throws an exception here.
    }
```

- \PHPJava\Packages\java\lang\StringBuilder#toString

```php
    public function toString(): _String
    {
        return new _String($this);
    }
```

**Comment by m3m0r7** [comment]
@chitoku-k 
Sorry! You need to change `String#hashCode` adding to the above.

```php
    public function hashCode($a = null)
    {
        if ($this->object instanceof _Utf8) {
            return spl_object_id($this->object);
        }
        return spl_object_id($this);
    }
```

**Comment by m3m0r7** [comment]
@chitoku-k 
May I close this issue?

**Comment by chitoku-k** [comment]
Yes, it was unintentionally left open.
