### ISSUE TITLE
PHPがJVMにonしているように見えるロゴ

### ISSUE THREAD

**Issue by nakamoto** [php-java/php-java#247]
# 実装を要望するにあたっての概要を教えてください
https://github.com/php-java/php-java/raw/master/docs/img/logo.png
のロゴは、PHPがJVMにonしているように見えるので、逆にしたらどうかと思いました。

# コードの一例

# 期待する結果
イラスト下手なので、イラストうまい友達にいって書いてもらったほうが良ければ教えて下さいね。

**Comment by m3m0r7** [comment]
ロゴ作るのは得意ではないので、お手数ですがいくつかロゴのコントリビュートしていただけますか。

※ 当リポジトリのメインコントリビュータと決議をした上でロゴの採択および非採択が決まるため、コントリビュートしていただいたロゴが採用されるとは限りません。この点はご留意およびご容赦ください。

**Comment by nakamoto** [comment]
週末に友達と会うので、聞いてみますね

**Comment by nakamotojp** [comment]
![php+Java(文字アリ)](https://user-images.githubusercontent.com/59001254/71308139-e44ad000-243b-11ea-9e0e-cb50b14b9077.png)
![php+Java](https://user-images.githubusercontent.com/59001254/71308141-e876ed80-243b-11ea-8e1b-efc8a09255c8.png)
イラストレーターのバナナピールさん作です。

**Comment by mpyw** [comment]
構図は結構好きだけど，元のように線じゃなくて面だけで表現したバージョンが見てみたい気がする

**Comment by nakamotojp** [comment]
すいません、頂いているご意見のイメージがつかないので教えて下さい。
具体的にどのような意味でしょうか？

**Comment by mpyw** [comment]
正直な感想を申し上げますと，配色や線の使い方から，元のロゴに比べるとややチープな印象がでてしまっているなというところです。今のところは元のロゴのほうが個人的には好みです。

![image](https://user-images.githubusercontent.com/1351893/71455939-84a54980-27da-11ea-8a69-cba9b10b5622.png)

↑のように，輪郭を表す黒い線を使わず面だけで表現するという意味ですね

**Comment by nakamotojp** [comment]
![23A53AE7-93F8-434A-BB2D-D1866D6B57BE](https://user-images.githubusercontent.com/59001254/71468699-3e67de80-280a-11ea-9dd8-725830492108.png)
![D4D254C4-1D1F-4EF5-9FB7-280A52B45BC7](https://user-images.githubusercontent.com/59001254/71468700-3e67de80-280a-11ea-8f56-fb5f39632d44.png)
どうでしょうか？

**Comment by nakamotojp** [comment]
片方が白
片方が透過
です。↑のみためでは分かりづらいので、デベロッパーツールで背景css変えたらわかりやすいですよ。

**Comment by mpyw** [comment]
@nakamotojp ありがとうございます，最初よりずっといい感じに見えます！

**Comment by m3m0r7** [comment]
@nakamotojp 
ありがとうございます！個人的にで恐縮ですが、テキストは要らないかなと思っています。
また、若干のジャギーが気になります。

**Comment by mpyw** [comment]
@nakamotojp 

- ジャギーを消す
- 文字を消す

に関しては memory さんと同意見です。個人的な意見としては

- 直線や曲線をできるだけなめらかにする<br>（手書き感はそんなに要らないかも…もしラフであれば恐縮です）

上記を実施した上で，さらに

- 正方形で切り抜いて象の後半身部分を落としてしまう

のほうがいい気もしてます。

![image](https://user-images.githubusercontent.com/1351893/71470637-298e4980-2810-11ea-804e-e7ea28bb39a0.png)

このロゴの前半身部分の構図はとても好きです！後半身部分がちょっと微妙で，いっそのこと「よく見たら象だ！」ってぐらいに抽象度を上げたロゴにしてしまうほうがいい気がしてます。

**Comment by m3m0r7** [comment]
@nakamotojp @mpyw 
いくつも変更点等お伝えしていて申し訳ございませんが、一旦ロゴを変更するか否かも含めてメインコントリビュータと協議の上、改めてこの issue にコメントさせていただければと思います。

最初にもお伝えしたように、ご希望に添えないこともございますので、その点はご容赦ください

**Comment by nakamotojp** [comment]
>> 正方形で切り抜いて象の後半身部分を落としてしまう

**Comment by nakamotojp** [comment]
ご丁寧にありがとうございます。
決まりましたら改めて教えて頂けると嬉しいです。

**Comment by nakamotojp** [comment]
![99D79E7F-0BE0-4260-A188-E3A8C636EE24](https://user-images.githubusercontent.com/59001254/71774398-4dd8eb80-2fb1-11ea-8be6-81b85208c98b.png)
![9D90974E-6685-4231-92F7-9993088C7C92](https://user-images.githubusercontent.com/59001254/71774399-4e718200-2fb1-11ea-8edd-2df497ded2c0.png)
![EE274800-DDF0-4F0B-B8A3-BE285CCCE17B](https://user-images.githubusercontent.com/59001254/71774400-4e718200-2fb1-11ea-8b69-35b524fa66d1.png)

イラストレーターからの気持ちです。
今年もよろしくお願いします。

**Comment by m3m0r7** [comment]
@nakamotojp 
ご連絡が遅くなり大変申し訳ございません。メインコントリビュータと慎重に決議させていただいた結果今回ロゴの変更は全般的に見送りとさせてください。
理由はいくつかありますが、下記が主な理由となります。

- 既存のロゴを変更することによる php-java に対するイメージが崩れてしまう恐れがあるため

以上です。本件恐れ入りますが issue をクローズとさせていただければと思います。
