### ISSUE TITLE
Fatal error Class String_ not found with default HelloWorld print

### ISSUE THREAD

**Issue by cyberformed** [php-java/php-java#270]
# Tell me your versions
- **PHP**

7.4

- **JDK**
1.8
- **PHPJava**
Latest using composer 
# Summary
Fatal error: Uncaught Error: Class 'String_' not found in C:\xampp\htdocs\java2php\vendor\php-java\php-java\src\Core\JVM\PHPClassInvoker.php:126

The default example is not working.

# Code
<?php

require 'vendor/autoload.php';

use PHPJava\Core\JavaClass;
use PHPJava\Core\Stream\Reader\FileReader;

 JavaClass::load('HelloWorld')
    ->getInvoker()
    ->getStatic()
    ->getMethods()
    ->call(
        'main',
        "Hello World!"
    );

// Or, you can specify file path as follows. 
/*
(new JavaClass(new JavaCompiledClass(new FileReader('HelloWorld.class'))))
    ->getInvoker()
    ->getStatic()
    ->getMethods()
    ->call(
        'main',
        ["Hello World!"]
    );
*/
?>
<img width="782" alt="Screenshot_1" src="https://user-images.githubusercontent.com/13065921/100499310-903d8500-318e-11eb-876e-dfe6a34119d0.png">
<img width="960" alt="Screenshot_2" src="https://user-images.githubusercontent.com/13065921/100499314-959acf80-318e-11eb-9e82-a35ebc7ec691.png">

# Expect

It should print Hello World
# Actual
Throws Exception Fatal error: Uncaught Error: Class 'String_' not found in C:\xampp\htdocs\java2php\vendor\php-java\php-java\src\Core\JVM\PHPClassInvoker.php:126

**Comment by cyberformed** [comment]
Is there any issue in the installation process. But it works with the java inbulit class like java.lang.Math and try to find the power of 2. It prints successfully the output as 16.

**Comment by m3m0r7** [comment]
@cyberformed 
Thanks for your reporting.

I didn't test on Windows platform.
I tested the default example on my machine macOS Big Sur, it works fine.

Seemingly, The composer didn't autoload.
And your tested code is incorrect because you did not wrap main method's parameters by `[` and `]`.

Your code: 
```
...getInvoker() ->getStatic() ->getMethods() ->call( 'main', "Hello World!" );
```

The correct code is here:
```
...getInvoker() ->getStatic() ->getMethods() ->call( 'main', ["Hello World!"]);
```

The main parameter is required `String[]`, not a `String`.

Please show me your Java file and mnemonics with `javap -v your-compiled-java-file` if it still doesn't works.

Thanks,

**Comment by jizhaogit** [comment]
I get the same issue while doing the hello world testing:

Here is my PHP code:
<?php
use PHPJava\Core\JavaClass;
require __DIR__ . '/vendor/autoload.php'; 

$class = JavaClass::load('HelloWorld');
$class->getInvoker()
    ->getStatic()
    ->getMethods()
    ->call( 'main', ["Hello World!"]);
?>

Java Code:
class HelloWorld 
{
    public static void main(String[] args)
    {
        System.out.println(args[0]);
    }
}

any advise? Thanks a lot!

**Comment by m3m0r7** [comment]
@jizhaogit 
What did you use OS? Windows is not tested.

Please check below if you use *nix.


- 1) Check file paths
```
$ tree .
.
├── HelloWorld.class
├── HelloWorld.java
└── HelloWorld.php
```


- 2) Check JDK Version
```
$ java -version
```


- 3) Please write this code from QuickStart
```php
<?php
require __DIR__ . '/vendor/autoload.php';

use PHPJava\Core\JavaClass;

JavaClass::load('HelloWorld')
    ->getInvoker()
    ->getStatic()
    ->getMethods()
    ->call(
        'main',
        ["Hello World!"]
    );

```

or

```php
<?php
require __DIR__ . '/vendor/autoload.php';

use PHPJava\Core\JavaClass;
use PHPJava\Core\JavaCompiledClass;
use PHPJava\Core\Stream\Reader\FileReader;

(new JavaClass(new JavaCompiledClass(new FileReader('HelloWorld.class'))))
    ->getInvoker()
    ->getStatic()
    ->getMethods()
    ->call(
        'main',
        ["Hello World!"]
    );

```

- 4) Run

```
$ php HelloWorld.php 
```

They are successful to run on my environment.

---
Or you should try `composer dump-autoload`
