### ISSUE TITLE
能正常使用吗？？？

### ISSUE THREAD

**Issue by dignfei** [php-java/php-java#272]
# Tell me your versions
- **PHP**
![image](https://user-images.githubusercontent.com/25482706/117103292-a63e1a00-adac-11eb-99e5-916b9af1a172.png)

- **JDK**

- **PHPJava**

# Summary

# Code

# Expect

# Actual

**Comment by m3m0r7** [comment]
@dignfei 
Please try QuickStart https://github.com/php-java/php-java#quick-start

**Comment by dignfei** [comment]
> @dignfei
> Please try QuickStart https://github.com/php-java/php-java#quick-start

可以运行.class文件。但是jar文件无法运行

**Comment by m3m0r7** [comment]
@dignfei 
Please read here: https://github.com/php-java/php-java#java-archive-execute-jar-file

And I cannot understand what you said, Please write in English or Japanese.
I'm using translator for your sentence.
