### ISSUE TITLE
Error runing jdk

### ISSUE THREAD

**Issue by godwindaniel101** [php-java/php-java#273]
# Tell me your versions
- **PHP** 8.0

- **JDK**17.0.1

- **PHPJava**

# Summary i get the response "Unsupported JDK version 61.0 " despite not using that version

# Code

# Expect

# Actual

**Comment by m3m0r7** [comment]
@godwindaniel101 
Please compile your java files with JDK 8 or 9 or 10 or 11.
or commit here https://github.com/php-java/php-java/blob/7fb5748576b9af8eaed30714fab0cc6c7bb1f14e/src/Kernel/Resolvers/SDKVersionResolver.php#L9-L21

**Comment by siketyan** [comment]
May be resolved by #275
