### ISSUE TITLE
 How to call this kind of frame correctly？

### ISSUE THREAD

**Issue by iMactool** [php-java/php-java#274]
# What do you want to implement?
 How to call this kind of frame correctly？
$ php -v
PHP 7.4.30 (cli)

$ java --version
openjdk 13.0.1 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

# Example Code
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/3078413/193030972-c40ea510-baf3-4b61-95e5-3917a47d7325.png">
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/3078413/193031280-2a84c37f-2fdb-4ef1-a72e-775104d92040.png">
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/3078413/193031409-744dc353-226e-48d3-9788-c07d37824d39.png">
<img width="850" alt="image" src="https://user-images.githubusercontent.com/3078413/193031459-40a8205c-4d4d-4c54-9486-0b62071f3084.png">

# Expect

**Comment by m3m0r7** [comment]
@iMactool 
Your code is wrong to call DemoApplication class.
Please check the built directory and change the current working directory to it.

and, to change the first parameter to below:
```php
JavaClass::load('com.demo.DemoApplication')->...
```

NOTE: The php-java is not tested solidly to call another packaged (e.g. jar) class.

**Comment by iMactool** [comment]
> @iMactool Your code is wrong to call DemoApplication class. Please check the built directory and change the current working directory to it.
> 
> and, to change the first parameter to below:
> 
> ```
> JavaClass::load('com.demo.DemoApplication')->...
> ```
> 
> NOTE: The php-java is not tested solidly to call another packaged (e.g. jar) class.

Thanks, I'll try it later. Thanks again :)
