### ISSUE TITLE
Inquiries about version up

### ISSUE THREAD

**Issue by chobyungkwon** [php-java/php-java#276]
I am trying to install through composer in visual studio code, but the following error occurs. Do you plan to upgrade the versions of the libraries you use?

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php-java/php-java dev-master -> satisfiable by php-java/php-java[dev-master].
    - php-java/php-java dev-master requires monolog/monolog ^2.2 -> found monolog/monolog[2.2.0, ..., 2.x-dev] but it conflicts with your root composer.json require (^3.0@dev).

**Comment by m3m0r7** [comment]
@chobyungkwon 

Please update/contribute the monolog version in the php-java.
https://github.com/php-java/php-java/blob/master/composer.json#L18

or

downgrade your monolog version in the composer.json

**Comment by m3m0r7** [comment]
if you don't know how to update the monolog in the php-java, I will update the monolog version however it takes more time because I'm very busy...

**Comment by m3m0r7** [comment]
Close this
